package Formularios;

import Clases.LogicaNotas;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Smit
 */
public final class ReporteNotas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteNotas
     */
    public ReporteNotas() {
        initComponents();
        //Mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        bs = new javax.swing.JTextField();
        n2 = new javax.swing.JLabel();
        btnbuscar1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        grado = new javax.swing.JComboBox<>();
        n10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        secc = new javax.swing.JComboBox<>();
        bsc3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Reporte Notas");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LG.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LISTA DE ALUMNOS : \"IE Amigos School\"");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1260, 40));

        bs.setBorder(null);
        getContentPane().add(bs, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 340, 40));

        n2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        n2.setText("Buscar:");
        getContentPane().add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 90, 40));

        btnbuscar1.setBackground(new java.awt.Color(51, 51, 255));
        btnbuscar1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnbuscar1.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/23.png"))); // NOI18N
        btnbuscar1.setText("BUSCAR");
        btnbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, -1, 40));

        jButton2.setBackground(new java.awt.Color(0, 204, 51));
        jButton2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/24.png"))); // NOI18N
        jButton2.setText("GENERAR REPORTE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, -1, 40));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 1220, 520));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 360, 20));

        grado.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        grado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecionar>", "1", "2", "3", "4", "5" }));
        getContentPane().add(grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 140, 30));

        n10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        n10.setText("Grado:");
        getContentPane().add(n10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Sección:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 60, 30));

        secc.setFont(new java.awt.Font("Roboto Condensed Light", 0, 14)); // NOI18N
        secc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecionar>", "A", "B", "C" }));
        getContentPane().add(secc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 140, 30));

        bsc3.setBackground(new java.awt.Color(0, 102, 51));
        bsc3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bsc3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/14.png"))); // NOI18N
        bsc3.setText("Mostrar");
        bsc3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bsc3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bsc3MouseExited(evt);
            }
        });
        bsc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsc3ActionPerformed(evt);
            }
        });
        getContentPane().add(bsc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar1ActionPerformed
        Buscar(Integer.parseInt(bs.getText()));
    }//GEN-LAST:event_btnbuscar1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GenerarReportePDF();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bsc3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsc3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bsc3MouseEntered

    private void bsc3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsc3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bsc3MouseExited

    private void bsc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsc3ActionPerformed
        int Grado = Integer.parseInt(grado.getSelectedItem().toString());
        String Seccion = secc.getSelectedItem().toString();
        Mostrar(Grado, Seccion);
    }//GEN-LAST:event_bsc3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bs;
    private javax.swing.JButton bsc3;
    private javax.swing.JButton btnbuscar1;
    private javax.swing.JComboBox<String> grado;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel n10;
    private javax.swing.JLabel n2;
    private javax.swing.JComboBox<String> secc;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
    
    private void GenerarReportePDF() {
        try {
        // Obtener el apellido del alumno para el nombre del archivo
            String apellidoAlumno = tabla.getValueAt(0, 6).toString(); // Ajusta el índice si es necesario
            String fileName = "Notas_" + apellidoAlumno + ".pdf";
            String fechaActual = new SimpleDateFormat("yyyy").format(new Date());

        // Crear documento PDF en formato horizontal
            Document document = new Document(PageSize.A4.rotate());
            PdfWriter.getInstance(document, new FileOutputStream(fileName));
            document.open();

        // Crear una tabla para el logo y el título
            PdfPTable headerTable = new PdfPTable(2);
            headerTable.setWidthPercentage(100);
            headerTable.setWidths(new float[]{1, 4});
            Paragraph titulo = new Paragraph("INFORME DE PROGRESO DEL APRENDIZAJE DEL ESTUDIANTE – " + fechaActual, FontFactory.getFont(FontFactory.HELVETICA_BOLD, 13));
            titulo.setAlignment(Element.ALIGN_CENTER);
            document.add(titulo);

        // Logo
            String logoPath = "C:\\Users\\Smit1\\OneDrive\\Documentos\\Proyectos\\JAVA\\Proyecto Amigos School -Version 3.1\\src\\Imagenes\\Escudo.png"; // Cambia esta ruta por la ruta de tu logo
            Image logo = Image.getInstance(logoPath);
            logo.scaleToFit(100, 100);
            logo.setAbsolutePosition(40, document.getPageSize().getHeight() - 140); // Ajustar posición para la orientación horizontal
            document.add(logo);
            document.add(Chunk.NEWLINE);

        // Información del grado, sección y tutor
            PdfPTable infoTable = new PdfPTable(4);
            infoTable.setWidthPercentage(70);
            infoTable.addCell(getColoredCell("DRE: ", PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
            infoTable.addCell(getColoredCell("LAMBAYEQUE", PdfPCell.ALIGN_CENTER, BaseColor.WHITE));
            infoTable.addCell(getColoredCell("UGEL:", PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
            infoTable.addCell(getColoredCell("CHICLAYO", PdfPCell.ALIGN_CENTER, BaseColor.WHITE));
        
            infoTable.addCell(getColoredCell("NIVEL: ", PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
            infoTable.addCell(getColoredCell("SECUNDARIA", PdfPCell.ALIGN_CENTER, BaseColor.WHITE));
            infoTable.addCell(getColoredCell("CODIGO MODULAR:", PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
            infoTable.addCell(getColoredCell("160465", PdfPCell.ALIGN_CENTER, BaseColor.WHITE));
            document.add(infoTable);
        
            PdfPTable infoTable2 = new PdfPTable(2);
            infoTable2.setWidthPercentage(70);
            infoTable2.addCell(getColoredCell("Institucion Educativa:", PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
            infoTable2.addCell(getColoredCell("I.E Amigos School", PdfPCell.ALIGN_CENTER, BaseColor.WHITE));
            document.add(infoTable2);
        
            PdfPTable infoTable3 = new PdfPTable(4);
            infoTable3.setWidthPercentage(70);
            infoTable3.addCell(getColoredCell("GRADO:", PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
            infoTable3.addCell(getColoredCell(tabla.getValueAt(0, 3).toString(), PdfPCell.ALIGN_CENTER, BaseColor.WHITE));
            infoTable3.addCell(getColoredCell("SECCION:", PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
            infoTable3.addCell(getColoredCell(tabla.getValueAt(0, 4).toString(), PdfPCell.ALIGN_CENTER, BaseColor.WHITE));
            document.add(infoTable3);
        
            PdfPTable infoTable4 = new PdfPTable(2);
            infoTable4.setWidthPercentage(70);
            infoTable4.addCell(getColoredCell("Apellidos y nombres del estudiante:", PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
            infoTable4.addCell(getColoredCell(tabla.getValueAt(0, 6).toString() + " " + tabla.getValueAt(0, 5).toString(), PdfPCell.ALIGN_CENTER, BaseColor.WHITE));
            document.add(infoTable4);
        
            PdfPTable infoTable5 = new PdfPTable(4);
            infoTable5.setWidthPercentage(70);
            infoTable5.addCell(getColoredCell("Codigo del estudiante:", PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
            infoTable5.addCell(getColoredCell(tabla.getValueAt(0, 0).toString(), PdfPCell.ALIGN_CENTER, BaseColor.WHITE));
            infoTable5.addCell(getColoredCell("DNI:", PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
            infoTable5.addCell(getColoredCell(tabla.getValueAt(0, 7).toString(), PdfPCell.ALIGN_CENTER, BaseColor.WHITE));
            document.add(infoTable5);
            document.add(Chunk.NEWLINE);

        // Tabla de cursos
            PdfPTable table = new PdfPTable(1); // Número de columnas ajustado según la imagen
            table.setWidthPercentage(100);
            table.addCell(getColoredCell("MALLA CURRICULAR", PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
            document.add(table);
        
            PdfPTable tab = new PdfPTable(6); // Número de columnas ajustado según la imagen
            tab.setWidthPercentage(100);
        
            tab.addCell(getColoredCell("CURSO", PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
            tab.addCell(getColoredCell("Primer Bimestre",  PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
            tab.addCell(getColoredCell("Segundo Bimestre",PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
            tab.addCell(getColoredCell("Tercer Bimestre",  PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
            tab.addCell(getColoredCell("Cuarto Bimestre", PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
            tab.addCell(getColoredCell("Calificacion Final", PdfPCell.ALIGN_CENTER, BaseColor.LIGHT_GRAY));
        // Aquí deberías agregar las filas de datos para los cursos, por ejemplo:
        // Asumiendo que tienes un DefaultTableModel llamado model que contiene los datos de la tabla
            DefaultTableModel model = (DefaultTableModel) tabla.getModel();
            int numRows = model.getRowCount();
            for (int i = 0; i < numRows; i++) {
                tab.addCell(getColoredCell(model.getValueAt(i, 8).toString(), PdfPCell.ALIGN_CENTER, BaseColor.WHITE)); // ÁREA CURRICULAR
                tab.addCell(getColoredCell(model.getValueAt(i, 9).toString(), PdfPCell.ALIGN_CENTER, BaseColor.WHITE)); // CALIFICATIVO POR PERIODO
                tab.addCell(getColoredCell(model.getValueAt(i, 10).toString(), PdfPCell.ALIGN_CENTER, BaseColor.WHITE)); // 1er Periodo
                tab.addCell(getColoredCell(model.getValueAt(i, 11).toString(), PdfPCell.ALIGN_CENTER, BaseColor.WHITE)); // 2do Periodo
                tab.addCell(getColoredCell(model.getValueAt(i, 12).toString(), PdfPCell.ALIGN_CENTER, BaseColor.WHITE)); // 3er Periodo
                tab.addCell(getColoredCell(model.getValueAt(i, 13).toString(), PdfPCell.ALIGN_CENTER, BaseColor.WHITE)); // 4to Periodo
            }

            document.add(tab);
            document.add(Chunk.NEWLINE);
            document.close();
            
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                File pdfFile = new File(fileName);
                if (pdfFile.exists()) {
                    desktop.open(pdfFile);
                }
            }

            System.out.println("PDF generado exitosamente!");
            JOptionPane.showMessageDialog(null, "PDF generado exitosamente!");

        } catch (DocumentException | HeadlessException | FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error al generar PDF: " + e.getMessage());
        } catch (IOException ex) {
            Logger.getLogger(ReporteMatriculas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private static PdfPCell getColoredCell(String text, int alignment, BaseColor bgColor) {
        PdfPCell cell = new PdfPCell(new Phrase(text));
        cell.setPadding(5);
        cell.setHorizontalAlignment(alignment);
        cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        cell.setBackgroundColor(bgColor);
        cell.setBorderColor(BaseColor.BLACK);
        return cell;
        }

    private static PdfPCell getCell(String text, int colspan, int alignment, BaseColor bgColor) {
        PdfPCell cell = new PdfPCell(new Phrase(text));
        cell.setColspan(colspan);
        cell.setHorizontalAlignment(alignment);
        cell.setPadding(5);
        cell.setBackgroundColor(bgColor);
        cell.setBorderColor(BaseColor.BLACK);
        return cell;
    }



    public void Buscar(int Codigo) {
        try {
            DefaultTableModel modelo;
            LogicaNotas fun = new LogicaNotas();
            modelo = fun.Buscarr_Reporte_Notas(Codigo);
            tabla.setModel(modelo);
            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    
    public void Mostrar(int r, String g) {
        try {
            DefaultTableModel modelo;
            LogicaNotas fun = new LogicaNotas();
            modelo = fun.Mostrar_Reporte_Notas(r, g);
            tabla.setModel(modelo);
            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    public void ocultar_columnas(){
        tabla.getColumnModel().getColumn(1).setMaxWidth(0);
        tabla.getColumnModel().getColumn(1).setMinWidth(0);
        tabla.getColumnModel().getColumn(1).setPreferredWidth(0);
        /////////////////////////////////////////////////////////
        tabla.getColumnModel().getColumn(2).setMaxWidth(0);
        tabla.getColumnModel().getColumn(2).setMinWidth(0);
        tabla.getColumnModel().getColumn(2).setPreferredWidth(0);
        /////////////////////////////////////////////////////////
    }
    
}
