package Formularios;

import Clases.ExportarExcel;
import Clases.LogicaProfesor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Smit
 */
public final class ReporteDocente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteNotas
     */
    public ReporteDocente() {
        initComponents();
        Mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtbuscar1 = new javax.swing.JTextField();
        n2 = new javax.swing.JLabel();
        btnbuscar1 = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        BottonExcel = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LISTA DE ALUMNOS : \"IE Amigos School\"");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1260, 40));

        txtbuscar1.setBorder(null);
        getContentPane().add(txtbuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 340, 40));

        n2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        n2.setText("Buscar:");
        getContentPane().add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 90, 40));

        btnbuscar1.setBackground(new java.awt.Color(51, 51, 255));
        btnbuscar1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnbuscar1.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/23.png"))); // NOI18N
        btnbuscar1.setText("BUSCAR");
        btnbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, -1, 40));

        total.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        total.setText("N° de Registros:");
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 150, -1, 40));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 1220, 520));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 360, 20));

        BottonExcel.setBackground(new java.awt.Color(0, 204, 51));
        BottonExcel.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        BottonExcel.setForeground(new java.awt.Color(255, 255, 255));
        BottonExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/24.png"))); // NOI18N
        BottonExcel.setText("GENERAR EXCEL");
        BottonExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonExcelActionPerformed(evt);
            }
        });
        getContentPane().add(BottonExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscar1ActionPerformed

    private void BottonExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonExcelActionPerformed
        ExportarExcel obj;

        try {
            obj = new ExportarExcel();
            obj.exportarExcel(tabla);
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_BottonExcelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BottonExcel;
    private javax.swing.JButton btnbuscar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel n2;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel total;
    private javax.swing.JTextField txtbuscar1;
    // End of variables declaration//GEN-END:variables
    
    public void ocultar_columnas(){
        tabla.getColumnModel().getColumn(0).setMaxWidth(0);
        tabla.getColumnModel().getColumn(0).setMinWidth(0);
        tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
    public void Mostrar() {
        try {
            DefaultTableModel modelo;
            LogicaProfesor func = new LogicaProfesor();
            modelo = func.Mostrar();
            tabla.setModel(modelo);
            ocultar_columnas();
            total.setText("Total Registros: " + func.totalregistros);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, "Error al mostrar los datos: " + e.getMessage());
        }
    }
}
